name: Resize Images

on:
  push:
    paths:
      - 'flier/**'

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Resize to 1444px width
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'flier'
          new-resolution: '1444x'
          output-folder: 'flier'
