name: Resize Images on Commit

on:
  push:
    branches: [ main ]      # main ブランチへのプッシュをトリガー
    paths:
      - 'flier/**'          # flier/ 配下の変更のみ検知

permissions:
  contents: write          # ファイルのコミット＆プッシュを許可

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p resized

      - name: Resize to 1444×2048
        uses: sharadcodes/img-resizer@v1.1
        with:
          image-folder: 'flier'
          new-resolution: '1444x2048'
          output-folder: 'resized'

      - name: Commit resized images
        uses: EndBug/add-and-commit@v9
        with:
          add: 'resized/**'
          author_name: 'github-actions[bot]'
          author_email: 'github-actions[bot]@users.noreply.github.com'
          message: 'chore: add resized images'
